version: "3.7"
services:
  db_starkoverflow:
    image: postgres:latest
    restart: always
    container_name: starkoverflow_dev_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      TZ: 'Europe/Zurich'
      PGTZ: 'Europe/Zurich'
    volumes:
      - ../../database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: starkoverflow_dev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@starkoverflow.ch
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    networks:
      - backend

networks:
  backend:
    external: false      