version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: starkoverflow_dev_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      TZ: 'Europe/Zurich'
      PGTZ: 'Europe/Zurich'
    volumes:
      - ../../database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"