version: "3.7"
services:
  starkoverflow-db:
    image: postgres:latest
    restart: always
    container_name: starkoverflow-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      TZ: 'Europe/Zurich'
      PGTZ: 'Europe/Zurich'
    volumes:
      - ../../database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - starkoverflow

  starkoverflow-pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: starkoverflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@starkoverflow.ch
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    networks:
      - starkoverflow
  gamificator-db:
    image: mysql
    restart: always
    container_name: gamificator-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=gamificator_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/:/docker-entrypoint-initdb.d/
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - gamificator

  gamificator-adminer:
    image: adminer
    container_name: gamificator-adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - gamificator-db
    networks:
      - gamificator

  gamificator-app:
    image: ghcr.io/digitalpatate/gamificator:latest
    container_name: gamificator-app
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://gamificator-db:3306/gamificator_db
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - gamificator-db
    ports:
      - 8080:8080
    networks:
      - gamificator


networks:
  starkoverflow:
    external: false
  gamificator:
    external: false
