version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@starkoverflow.ch
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
      # set timezone to UTC+2
      TZ: 'Europe/Zurich'
      PGTZ: 'Europe/Zurich'
    ports:
      - "8081:80"
    links:
      - "db:pgsql-server"


  web:
    image: ghcr.io/digitalpatate/starkoverflow:latest
    container_name: starkoverflow
    ports:
      - "9080:9080"
    volumes:
      - ./src/main/liberty/config/server.env:/config/server.env
    depends_on:
      - db