version: '3'
services:
  db:
    image: postgres:latest
    container_name: e2e_test_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    networks:
      - backend
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  backend:
    image: ghcr.io/digitalpatate/starkoverflow:latest
    container_name: e2e_test_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: stark_db
      DB_USER: admin
      DB_PASSWORD: secret
    depends_on:
      - db
    ports:
     - "9080:9080"
    networks:
      - backend
networks:
  backend:
    external: false